stackName: test-cumulus
bucket: cumulus-test-sandbox-internal
DiscoverAndQueuePdrs: &defaults
  meta:
    stack: test-cumulus
    buckets:
      internal: cumulus-test-sandbox-internal
    templates:
      ParsePdr: s3://cumulus-test-sandbox-internal/test-cumulus/workflows/ParsePdr.json
    queues:
      startSF: https://sqs.us-east-1.amazonaws.com/{{AWS_ACCOUNT_ID}}/test-cumulus-startSF
ParsePdr: *defaults
