
default:
  stackName: test-cumulus
  stackNameNoDash: TestCumulus

  apiStage: dev

  vpc:
    vpcId: vpc-5bb23422
    subnets:
      - subnet-ae2ba1f4

  ecs:
    instanceType: t2.micro

  buckets:
    internal: cumulus-test-sandbox-internal

  iams:
    ecsRoleArn: arn:aws:iam::433612427488:role/ghrc-cumulus-ecs
    lambdaApiGatewayRoleArn: arn:aws:iam::433612427488:role/ghrc-cumulus-lambda-api-gateway
    lambdaProcessingRoleArn: arn:aws:iam::433612427488:role/ghrc-cumulus-lambda-processing
    stepRoleArn: arn:aws:iam::433612427488:role/ghrc-cumulus-steprole
    instanceProfile: arn:aws:iam::433612427488:instance-profile/ghrc-cumulus-ecs

    urs_url: https://uat.urs.earthdata.nasa.gov/ #make sure to include the trailing slash

    # if not specified the value of the apigateway backend endpoint is used
    # api_backend_url: https://apigateway-url-to-api-backend/ #make sure to include the trailing slash

    # if not specified the value of the apigateway dist url is used
    # api_distribution_url: https://apigateway-url-to-distribution-app/ #make sure to include the trailing slash

  # URS users who should have access to the dashboard application.
  users:
    - username: lfrederick


lf-test:

  vpc:
    vpcId: vpc-5bb23422
    subnets:
      - subnet-ae2ba1f4

  iams:
    ecsRoleArn: arn:aws:iam::596205514787:role/test-cumulus-ecs
    lambdaApiGatewayRoleArn: arn:aws:iam::596205514787:role/test-cumulus-lambda-api-gateway
    lambdaProcessingRoleArn: arn:aws:iam::596205514787:role/test-cumulus-lambda-processing
    stepRoleArn: arn:aws:iam::596205514787:role/test-cumulus-steprole
    instanceProfile: arn:aws:iam::596205514787:instance-profile/test-cumulus-ecs
