default:
  stackName: aimee-deploy-cumulus
  stackNameNoDash: AimeeDeployCumulus

  vpc:
    vpcId: vpc-e61ddf9e
    subnets:
      - subnet-ef13ced0

  ecs:
    instanceType: t2.micro
    desiredInstances: 0
    availabilityZone: us-east-1e

  buckets:
    internal: cumulus-devseed-internal

  iams:
    urs_url: https://uat.urs.earthdata.nasa.gov/ #make sure to include the trailing slash
    ecsRoleArn: arn:aws:iam::433612427488:role/aimee-deploy-ecs
    lambdaApiGatewayRoleArn: arn:aws:iam::433612427488:role/aimee-deploy-lambda-api-gateway
    lambdaProcessingRoleArn: arn:aws:iam::433612427488:role/aimee-deploy-lambda-processing
    stepRoleArn: arn:aws:iam::433612427488:role/aimee-deploy-steprole
    instanceProfile: arn:aws:iam::433612427488:instance-profile/aimee-deploy-ecs

    # if not specified the value of the apigateway backend endpoint is used
    # api_backend_url: https://apigateway-url-to-api-backend/ #make sure to include the trailing slash

    # if not specified the value of the apigateway dist url is used
    # api_distribution_url: https://apigateway-url-to-distribution-app/ #make sure to include the trailing slash

  # URS users who should have access to the dashboard application.
  users:
    - username: aimeeb
