stackName: test-cumulus-integration
bucket: cumulus-test-sandbox-internal
DiscoverAndQueuePdrs: &defaults
  meta: &meta_config
    stack: test-cumulus-integration
    buckets:
      internal: cumulus-test-sandbox-internal
      private: cumulus-test-sandbox-private
    templates:
      ParsePdr: s3://cumulus-test-sandbox-internal/test-cumulus-integration/workflows/ParsePdr.json
      IngestGranule: s3://cumulus-test-sandbox-internal/test-cumulus-integration/workflows/IngestGranule.json
    queues:
      startSF: https://sqs.us-east-1.amazonaws.com/{{AWS_ACCOUNT_ID}}/test-cumulus-integration-startSF
ParsePdr:
  <<: *defaults
  meta:
    <<: *meta_config
    topic_arn: arn:aws:sns:us-east-1:{{AWS_ACCOUNT_ID}}:test-cumulus-integration-sftrackerSns-1L7I06L3O2FOI
IngestGranule:
  <<: *defaults
  SyncGranuleOutput:
    granules:
      - files:
        - bucket: cumulus-test-sandbox-private
          filename: s3://cumulus-test-sandbox-private/MOD09GQ.A2016358.h13v04.006.2016360104606.hdf
        - bucket: cumulus-test-sandbox-private
          filename: s3://cumulus-test-sandbox-private/MOD09GQ.A2016358.h13v04.006.2016360104606.hdf.met
