default:
  prefix: test-cumulus
  stackName: test-cumulus-iam
  authorizor: false
  capabilities:
    - CAPABILITY_NAMED_IAM
  buckets:
    internal: cumulus-test-sandbox-internal

  params:
     - name: ResourcePrefix
       value: '{{prefix}}'
     - name: InternalBucketName
       value: '{{buckets.internal}}'
     - name: PrivateBucketName
       value: '{{buckets.private}}'
     - name: ProtectedBucketName
       value: '{{buckets.protected}}'
     - name: PublicBucketName
       value: '{{buckets.public}}'
