default:
  prefix: test-cumulus-intg
  stackName: test-cumulus-intg-deployer
  stackNameNoDash: testCumulusIntgDeployer
  buckets:
    internal: cumulus-test-sandbox-internal
  capabilities:
    - CAPABILITY_IAM

  params:
    - name: Prefix
      value: '{{prefix}}'
    - name: StateMachinePrefix
      value: '{{stackNameNoDash}}'
    - name: InternalBucketName
      value: '{{buckets.internal}}'

